language: node_js

node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14

env:
  global:
    - COVERALLS_PARALLEL=true

after_success: npm run coverage

notifications:
  webhooks: https://coveralls.io/webhook
