language: node_js

node_js:
  - 10
  - 11
  - 12
  - 13
  - 14

jobs:
  include:
    - node_js: 4
      install: npm install nyc@^11 mocha@^3 chai@^3 coveralls@^2
    - node_js: 5
      install: npm install nyc@^11 mocha@^4 chai@^4 coveralls@^2
    - node_js: 6
      install: npm install nyc@^14 mocha@^6 chai@^4 coveralls@^3
    - node_js: 7
      install: npm install nyc@^14 mocha@^6 chai@^4 coveralls@^3
    - node_js: 8
      install: npm install nyc@^15 mocha@^7 chai@^4 coveralls@^3
    - node_js: 9
      install: npm install nyc@^15 mocha@^7 chai@^4 coveralls@^3

env:
  global:
    - COVERALLS_PARALLEL=true

install: npm install nyc@^15 mocha@^8 chai@^4 coveralls@^3

after_success: npm run coverage

notifications:
  webhooks: https://coveralls.io/webhook
