language: node_js

node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14

jobs:
  include:
    - node_js: 4
      install: npm install mocha@^3 chai@^3
    - node_js: 5
    - node_js: 6
    - node_js: 7

env:
  global:
    - COVERALLS_PARALLEL=true

install: npm install nyc mocha chai

after_success: npm run coverage

notifications:
  webhooks: https://coveralls.io/webhook
